# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "zing"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Samuel Chandra"]
  s.date = "2013-04-17"
  s.description = "This gem will generate common code for a new or existing Sinatra project"
  s.email = "samuelchandra@yahoo.com"
  s.executables = ["zing"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/zing",
    "lib/zing.rb",
    "lib/zing/command_parser.rb",
    "lib/zing/db_helper.rb",
    "lib/zing/file_helper.rb",
    "lib/zing/file_templates/base/models/admin_user.rb.erb",
    "lib/zing/file_templates/base/routes/cms.rb.erb",
    "lib/zing/file_templates/base/views/dashboard.haml.erb",
    "lib/zing/file_templates/base/views/layout.haml.erb",
    "lib/zing/file_templates/base/views/login.haml.erb",
    "lib/zing/file_templates/base/views/sidebar.haml.erb",
    "lib/zing/file_templates/push/models/apn_log.rb.erb",
    "lib/zing/file_templates/push/models/notification.rb.erb",
    "lib/zing/file_templates/push/models/token.rb.erb",
    "lib/zing/file_templates/push/push/push.rb.erb",
    "test/helper.rb",
    "test/test_zing.rb"
  ]
  s.homepage = "http://github.com/samchandra/zing"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Zing is Sinatra code generator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

